apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodetest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harbinman/argocd.git
    targetRevision: dev
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true